### ISSUE TITLE
Error created by not using targeting platform node correctly

### ISSUE THREAD

**Issue by nosferatu500** [CryogenicPlanet/depp#7]
nodejs - 17.0.1
macOS - 12.0.1

```
Errors [{ Could not resolve "vm" (use "Platform: api.PlatformNode" when building for node) 0xc006a4baa0 [] <nil>} { Could not resolve "perf_hooks" (use "Platform: api.PlatformNode" when building for node) 0xc006a4bb00 [] <nil>}]
```

PS: I have two MacBooks with the same configuration & environment. On MacBook 13 everything okay, but on MacBook 16 I got that issue.

**Comment by CryogenicPlanet** [comment]
Hey thanks for reaching out.

This error is created because `esbuild` is not able to bundle `vm` and `perf_hooks` the way to solve this is using the `--externals (-e)` flag. If you look at this https://github.com/CryogenicPlanet/depp#example-advanced-usage you should see an example of the usage.

Not entirely sure what is happening between the two MacBooks but I can investigate further and see if there is a related esbuild issue

**Comment by CryogenicPlanet** [comment]
Actually nvm I realized that I wasn't targeting the platform node correctly and will patch this in a newer version should fix these external problems. My bad
